[package]
name = "cdeps"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
clap = { version = "4.5.17", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
wasmparser = "0.217.0"
wit-parser = "0.217.0"
wat = "1.217.0"
wit-component = "0.217.0"
wit-bindgen-rust = "0.32.0"
wit-bindgen-core = "0.32.0"
url = "2.5.2"
