[package]
name = "spin-deps"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
clap = { version = "4.5.17", features = ["derive"] }
dialoguer = "0.11.0"
reqwest = "0.12.7"
sha2 = "0.10.8"
spin-manifest = { path = "/Users/karthik_ganeshram/Work/fermyon/spin/crates/manifest" }
spin-serde = { path = "/Users/karthik_ganeshram/Work/fermyon/spin/crates/serde" }
spin-loader = { path = "/Users/karthik_ganeshram/Work/fermyon/spin/crates/loader" }
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
toml_edit = "0.22.21"
url = "2.5.2"
wasmparser = { git = "https://github.com/bytecodealliance/wasm-tools" }
wit-component = { git = "https://github.com/bytecodealliance/wasm-tools" }
wit-parser = { git = "https://github.com/bytecodealliance/wasm-tools" }
wasm-pkg-loader = "0.4.1"
futures = "0.3.30"
semver = "1.0.23"
